<template>
  <div class="mypage">
    <div class="row">
      <span class="let" id="q">q</span>
      <span class="let" id="w">w</span>
      <span class="let" id="e">e</span>
      <span class="let" id="r">r</span>
      <span class="let" id="t">t</span>
      <span class="let" id="y">y</span>
      <span class="let" id="u">u</span>
      <span class="let" id="i">i</span>
      <span class="let" id="o">o</span>
      <span class="let" id="p">p</span>
    </div>
    <div class="row">
      <span class="let" id="a">a</span>
      <span class="let" id="s">s</span>
      <span class="let" id="d">d</span>
      <span class="let" id="f">f</span>
      <span class="let" id="g">g</span>
      <span class="let" id="h">h</span>
      <span class="let" id="j">j</span>
      <span class="let" id="k">k</span>
      <span class="let" id="l">l</span>
    </div>
    <div class="row">
      <span class="let" id="z">z</span>
      <span class="let" id="x">x</span>
      <span class="let" id="c">c</span>
      <span class="let" id="v">v</span>
      <span class="let" id="b">b</span>
      <span class="let" id="n">n</span>
      <span class="let" id="m">m</span>
    </div>

    <div class="rules">
      游戏规则：
      绿色为字母正确，棕色为含有该字母但位置不正确，红色为不包含此字母
    </div>
    <form name="myform" class="myform">
      <input
        @keyup="upkey($event, ind - 1)"
        @focus="befocus(ind)"
        class="inp"
        maxlength="1"
        type="text"
        v-for="ind in 6"
        :key="ind"
      />
    </form>
    <div class="butt">
      <button @click="def()" class="confirm">确定</button>
    </div>
    <div v-for="(wor,index) in enterarr" :key="index">
      <span  v-for="(t, ind) in wor" :key="ind + 1">
        <span v-if="t == world[ind]" class="downlet true">{{t}}</span>
        <span v-else-if="world.indexOf(t) != -1" class="downlet have">{{t}}</span>
        <span v-else class="downlet unhave">{{t}}</span>
      </span>
    </div>
  </div>
</template>

<script>
export default {
  name: "HelloWorld",
  data() {
    return {
      msg: "Welcome to Your Vue.js App",
      enterarr: [],
      tes: "tailor",
      undoublearr: [
        "tailor",
        "wicked",
        "chaser",
        "hostel",
        "jumper",
        "glance",
        "gospel",
        "goblin",
        "widely",
        "dragon",
        "polish",
        "course",
        "burden",
        "bundle",
        "Danish",
        "launch",
        "stifle",
        "ascent",
        "framed",
        "travel",
        "unload",
        "docile",
        "buckle",
        "valued",
        "pricey",
        "income",
        "revamp",
        "forage",
        "curved",
        "eulogy",
        "fiance",
        "fruity",
        "frugal",
        "profit",
        "frozen",
        "beyond",
        "caring",
        "humble",
        "stroke",
        "sickly",
        "forest",
        "resign",
        "quirky",
        "waving",
        "notice",
        "square",
        "nicely",
        "depict",
        "sprint",
        "anthem",
        "French",
        "runway",
        "warmly",
        "bumper",
        "myself",
        "lumber",
        "lyrics",
        "inform",
        "fumble",
        "stride",
        "grumpy",
        "stigma",
        "steamy",
        "blonde",
        "purely",
        "honest",
        "hockey",
        "untold",
        "fleshy",
        "sorely",
        "hairdo",
        "policy",
        "feisty",
        "swivel",
        "corpus",
        "course",
        "famine",
        "rinsed",
        "fathom",
        "climax",
        "wisdom",
        "budget",
        "enigma",
        "switch",
        "clamor",
        "menial",
        "lavish",
        "doubly",
        "invert",
        "backup",
        "sodium",
        "greasy",
        "wonder",
        "paving",
        "parcel",
        "permit",
        "ration",
        "ticker",
        "ascend",
        "clergy",
        "update",
        "chosen",
        "barely",
        "patrol",
        "shower",
        "powder",
        "joyful",
        "virtue",
        "purity",
        "rabies",
        "hiatus",
        "tundra",
        "impose",
        "fairly",
        "racket",
        "stroke",
        "surely",
        "flawed",
        "dimple",
        "payout",
        "design",
        "steady",
        "square",
        "spring",
        "flying",
        "peanut",
        "injury",
        "remind",
        "cradle",
        "chapel",
        "sludge",
        "charge",
        "shiver",
        "medial",
        "shrink",
        "Mojave",
        "atomic",
        "shroud",
        "marble",
        "finger",
        "single",
        "unable",
        "modern",
        "export",
        "homily",
        "strand",
        "author",
        "deport",
        "misery",
        "artful",
        "halter",
        "dilate",
        "sacred",
        "pantry",
        "sitcom",
        "Quaker",
        "snatch",
        "reason",
        "uptown",
        "bleach",
        "fabric",
        "abduct",
        "unfold",
        "strike",
        "wanted",
        "pointy",
        "feudal",
        "sniper",
        "sorbet",
        "branch",
        "margin",
        "baking",
        "racist",
        "mental",
        "whilst",
        "upload",
        "pucker",
        "easily",
        "toward",
        "fringe",
        "outlaw",
        "buying",
        "motive",
        "faster",
        "tumble",
        "trifle",
        "spiral",
        "simple",
        "behind",
        "ranked",
        "second",
        "upward",
        "amused",
        "flinch",
        "guitar",
        "native",
        "packed",
        "sprawl",
        "cruise",
        "abused",
        "sugary",
        "wrench",
        "pastry",
        "direct",
        "bronze",
        "comedy",
        "master",
        "gothic",
        "touchy",
        "govern",
        "median",
        "insert",
        "rocket",
        "shrine",
        "closet",
        "random",
        "ground",
        "figure",
        "covert",
        "frying",
        "dismal",
        "queasy",
        "cringe",
        "nicety",
        "bestow",
        "morsel",
        "stable",
        "bishop",
        "amidst",
        "number",
        "chrome",
        "jungle",
        "losing",
        "finale",
        "subtly",
        "musing",
        "spruce",
        "squirm",
        "patron",
        "visual",
        "jurist",
        "unpaid",
        "single",
        "amount",
        "timbre",
        "partly",
        "tackle",
        "banish",
        "herald",
        "pliers",
        "plaque",
        "slight",
        "unwise",
        "client",
        "grimly",
        "mystic",
        "orphan",
        "single",
        "casket",
        "double",
        "herald",
        "Jesuit",
        "armpit",
        "shaker",
        "casino",
        "phrase",
        "script",
        "sprint",
        "biased",
        "survey",
        "detach",
        "guinea",
        "obtain",
        "Polish",
        "United",
        "hacker",
        "Sabine",
        "fumble",
        "engulf",
        "serial",
        "wither",
        "urgent",
        "breach",
        "loving",
        "advice",
        "Briton",
        "micron",
        "mentor",
        "notify",
        "litmus",
        "golden",
        "insure",
        "budget",
        "almost",
        "pastel",
        "minute",
        "tinker",
        "shovel",
        "acting",
        "itself",
        "market",
        "Nordic",
        "unlock",
        "nature",
        "alcove",
        "mating",
        "factor",
        "marked",
        "coward",
        "strife",
        "ordain",
        "shriek",
        "masked",
        "molten",
        "father",
        "bistro",
        "carpet",
        "richly",
        "finely",
        "bluish",
        "expand",
        "ransom",
        "jumble",
        "unlike",
        "sliced",
        "piston",
        "starve",
        "nearby",
        "sporty",
        "watery",
        "steady",
        "stingy",
        "sewing",
        "admire",
        "period",
        "format",
        "abrupt",
        "signal",
        "typing",
        "eighty",
        "gamble",
        "hybrid",
        "clause",
        "crying",
        "influx",
        "bandit",
        "falcon",
        "salute",
        "person",
        "unveil",
        "locker",
        "darken",
        "warmth",
        "wonder",
        "burned",
        "wrench",
        "plague",
        "hunter",
        "silent",
        "thirds",
        "bicker",
        "mentor",
        "market",
        "antler",
        "pocket",
        "pencil",
        "inflow",
        "shield",
        "absent",
        "marvel",
        "behalf",
        "goblet",
        "solemn",
        "hybrid",
        "orange",
        "viable",
        "safety",
        "savior",
        "vector",
        "damper",
        "acting",
        "aspect",
        "winter",
        "candor",
        "insert",
        "drying",
        "cousin",
        "social",
        "erotic",
        "answer",
        "tubing",
        "sticky",
        "pastor",
        "squeak",
        "unholy",
        "figure",
        "closer",
        "permit",
        "injure",
        "fridge",
        "ground",
        "banker",
        "outing",
        "chives",
        "polite",
        "morale",
        "crayon",
        "holder",
        "backup",
        "adrift",
        "kosher",
        "shovel",
        "tribal",
        "keypad",
        "bright",
        "folder",
        "tuxedo",
        "fiasco",
        "raised",
        "shrewd",
        "exhort",
        "cradle",
        "anchor",
        "uptake",
        "lichen",
        "pundit",
        "ration",
        "doable",
        "ruined",
        "twinge",
        "quench",
        "hoarse",
        "climax",
        "forged",
        "enlist",
        "intake",
        "racism",
        "cortex",
        "frosty",
        "beacon",
        "legion",
        "shadow",
        "player",
        "ruling",
        "string",
        "darkly",
        "jingle",
        "antics",
        "Syrian",
        "upland",
        "amount",
        "humble",
        "sinful",
        "kitsch",
        "trying",
        "dreamy",
        "pounce",
        "punish",
        "answer",
        "object",
        "skimpy",
        "shrimp",
        "rowing",
        "novice",
        "filter",
        "socket",
        "linked",
        "oyster",
        "dilute",
        "debris",
        "sprout",
        "thanks",
        "exodus",
        "convey",
        "slouch",
        "square",
        "cobalt",
        "stream",
        "parish",
        "heroin",
        "ramble",
        "tanker",
        "lawyer",
        "burlap",
        "rejoin",
        "uptown",
        "blower",
        "hurtle",
        "thread",
        "clumsy",
        "module",
        "worthy",
        "unreal",
        "beckon",
        "mosaic",
        "hurdle",
        "asking",
        "humane",
        "mashed",
        "dismay",
        "police",
        "nearby",
        "subtle",
        "hauler",
        "shaved",
        "lesion",
        "charge",
        "sentry",
        "growth",
        "spoken",
        "mobile",
        "ground",
        "impart",
        "timely",
        "design",
        "metric",
        "phrase",
        "hustle",
        "embark",
        "pickle",
        "beyond",
        "lizard",
        "abound",
        "exotic",
        "danger",
        "mighty",
        "earthy",
        "worthy",
        "proven",
        "bridal",
        "rusted",
        "adjust",
        "turnip",
        "German",
        "choral",
        "behold",
        "silken",
        "rental",
        "layout",
        "poetry",
        "violet",
        "faucet",
        "denial",
        "corpse",
        "hermit",
        "seldom",
        "schema",
        "preach",
        "washed",
        "melody",
        "ratify",
        "nectar",
        "direct",
        "carbon",
        "object",
        "breach",
        "bushel",
        "winged",
        "forage",
        "Korean",
        "walnut",
        "racing",
        "rating",
        "thinly",
        "result",
        "tirade",
        "mystic",
        "sector",
        "public",
        "prison",
        "throes",
        "strain",
        "search",
        "mostly",
        "quartz",
        "muster",
        "embody",
        "normal",
        "jockey",
        "upshot",
        "recoup",
        "saving",
        "blanch",
        "sponge",
        "pirate",
        "employ",
        "sturdy",
        "unrest",
        "island",
        "tickle",
        "outage",
        "spring",
        "Jewish",
        "taxing",
        "makeup",
        "detain",
        "muscle",
        "parked",
        "escort",
        "chisel",
        "mature",
        "codify",
        "dosage",
        "python",
        "sunlit",
        "inhale",
        "saline",
        "source",
        "garish",
        "thrive",
        "bridge",
        "sequin",
        "homage",
        "kidney",
        "enough",
        "buckle",
        "modest",
        "rumble",
        "urchin",
        "triple",
        "editor",
        "duster",
        "packet",
        "priest",
        "custom",
        "Somali",
        "corset",
        "flower",
        "bakery",
        "bygone",
        "asylum",
        "German",
        "master",
        "hungry",
        "umpire",
        "marvel",
        "squint",
        "psyche",
        "signed",
        "linger",
        "manure",
        "midget",
        "zenith",
        "flower",
        "blight",
        "coping",
        "flavor",
        "Jesuit",
        "spongy",
        "drench",
        "strong",
        "amends",
        "wizard",
        "retain",
        "broach",
        "pander",
        "racing",
        "detour",
        "chorus",
        "launch",
        "absurd",
        "creamy",
        "biopsy",
        "coming",
        "linear",
        "lounge",
        "binder",
        "paltry",
        "kindly",
        "deploy",
        "strike",
        "spying",
        "insect",
        "trance",
        "loader",
        "pelvic",
        "friend",
        "turkey",
        "tumble",
        "anyhow",
        "tandem",
        "softly",
        "betray",
        "ornate",
        "parody",
        "hinder",
        "gently",
        "portal",
        "inmate",
        "purify",
        "bruise",
        "column",
        "dangle",
        "junior",
        "teacup",
        "unfair",
        "symbol",
        "tingle",
        "wisely",
        "survey",
        "campus",
        "escort",
        "foster",
        "morbid",
        "midway",
        "squawk",
        "coding",
        "plenty",
        "sweaty",
        "soaked",
        "wintry",
        "goalie",
        "mainly",
        "liquor",
        "skater",
        "poster",
        "torque",
        "tricky",
        "sculpt",
        "tragic",
        "staple",
        "lounge",
        "making",
        "cajole",
        "safely",
        "pastel",
        "washer",
        "listen",
        "retina",
        "public",
        "retail",
        "vendor",
        "streak",
        "overly",
        "matron",
        "praise",
        "advise",
        "ritual",
        "brazen",
        "replay",
        "branch",
        "openly",
        "loathe",
        "arched",
        "hearty",
        "harden",
        "hatred",
        "sultan",
        "crafty",
        "consul",
        "sleazy",
        "bundle",
        "cinder",
        "casing",
        "tangle",
        "boiled",
        "alpine",
        "citrus",
        "shield",
        "relish",
        "sample",
        "revolt",
        "search",
        "script",
        "devour",
        "Slavic",
        "eating",
        "dearly",
        "bridle",
        "silver",
        "stymie",
        "confer",
        "submit",
        "venous",
        "soften",
        "jacket",
        "inward",
        "triple",
        "tavern",
        "donkey",
        "tamper",
        "mobile",
        "adjoin",
        "reckon",
        "clique",
        "shanty",
        "reason",
        "failed",
        "depart",
        "justly",
        "bemoan",
        "Syrian",
        "median",
        "quiver",
        "spread",
        "minced",
        "anchor",
        "length",
        "warped",
        "backer",
        "divert",
        "digest",
        "fidget",
        "double",
        "stocky",
        "active",
        "should",
        "victor",
        "squirt",
        "tackle",
        "fading",
        "bodily",
        "refund",
        "export",
        "browse",
        "waking",
        "impact",
        "couple",
        "writhe",
        "plague",
        "turban",
        "scream",
        "upward",
        "French",
        "neatly",
        "stupid",
        "sortie",
        "reload",
        "sleigh",
        "stench",
        "random",
        "picket",
        "sultry",
        "absent",
        "frothy",
        "dismay",
        "amulet",
        "loafer",
        "lineup",
        "onward",
        "mister",
        "plight",
        "somber",
        "camper",
        "cavern",
        "dearth",
        "broken",
        "helium",
        "weight",
        "muscle",
        "fusion",
        "zealot",
        "method",
        "chisel",
        "guilty",
        "cruise",
        "moving",
        "golfer",
        "second",
        "scrape",
        "bridge",
        "biceps",
        "senior",
        "carved",
        "donate",
        "salute",
        "kidnap",
        "tripod",
        "deftly",
        "filter",
        "detail",
        "brutal",
        "nebula",
        "postal",
        "handle",
        "detail",
        "credit",
        "soiled",
        "scrawl",
        "flight",
        "herbal",
        "thread",
        "trendy",
        "stripe",
        "credit",
        "rodent",
        "formal",
        "uphold",
        "weight",
        "flashy",
        "genial",
        "prince",
        "blonde",
        "finger",
        "humbly",
        "sundae",
        "agency",
        "lander",
        "region",
        "morgue",
        "suitor",
        "jargon",
        "shadow",
        "grainy",
        "placid",
        "frenzy",
        "stored",
        "behind",
        "patrol",
        "marine",
        "burial",
        "hourly",
        "retail",
        "equity",
        "closed",
        "garden",
        "spread",
        "during",
        "glance",
        "signal",
        "change",
        "uneasy",
        "atrium",
        "sickle",
        "swivel",
        "timber",
        "bodice",
        "hotbed",
        "canopy",
        "sprawl",
        "clothe",
        "around",
        "forced",
        "winery",
        "invade",
        "smoker",
        "prized",
        "mother",
        "quaint",
        "stolen",
        "perish",
        "angler",
        "salmon",
        "parity",
        "warden",
        "gloved",
        "pigeon",
        "spruce",
        "glazed",
        "pistol",
        "switch",
        "family",
        "police",
        "upside",
        "candle",
        "travel",
        "streak",
        "belong",
        "trophy",
        "unpack",
        "knight",
        "barley",
        "gamble",
        "sermon",
        "malice",
        "mighty",
        "shroud",
        "poetic",
        "afield",
        "ignore",
        "mingle",
        "maiden",
        "debunk",
        "enmity",
        "boring",
        "mutiny",
        "pocket",
        "trough",
        "orgasm",
        "pacify",
        "syntax",
        "molest",
        "famous",
        "chunky",
        "carton",
        "starch",
        "driven",
        "heroic",
        "plunge",
        "squeal",
        "volume",
        "cranky",
        "worsen",
        "castle",
        "sketch",
        "dialog",
        "Baltic",
        "mishap",
        "winter",
        "burden",
        "county",
        "unlike",
        "gazebo",
        "scared",
        "double",
        "kindle",
        "mosque",
        "hardly",
        "siphon",
        "shower",
        "wasted",
        "marine",
        "sicken",
        "meadow",
        "tangle",
        "studio",
        "bowler",
        "fourth",
        "varied",
        "spinal",
        "slogan",
        "embryo",
        "felony",
        "jockey",
        "violet",
        "litany",
        "singer",
        "fabled",
        "locate",
        "homely",
        "revolt",
        "pathos",
        "deputy",
        "glitch",
        "native",
        "foster",
        "minute",
        "spiral",
        "string",
        "vastly",
        "ardent",
        "usable",
        "flimsy",
        "glitzy",
        "jigsaw",
        "censor",
        "warily",
        "junkie",
        "hamlet",
        "fisher",
        "utopia",
        "disarm",
        "boxing",
        "banter",
        "gambit",
        "superb",
        "hustle",
        "senior",
        "labour",
        "stormy",
        "throne",
        "change",
        "regain",
        "notice",
        "powder",
        "dental",
        "verbal",
        "number",
        "debtor",
        "combat",
        "mosaic",
        "lumbar",
        "course",
        "smoked",
        "grouse",
        "strain",
        "octave",
        "pardon",
        "entail",
        "faulty",
        "bunker",
        "visage",
        "caring",
        "inward",
        "forbid",
        "bruise",
        "gravel",
        "slider",
        "nickel",
        "matrix",
        "cougar",
        "orchid",
        "solace",
        "dainty",
        "crispy",
        "compel",
        "oxygen",
        "saying",
        "filthy",
        "boyish",
        "hunger",
        "clamor",
        "fresco",
        "vanity",
        "nimble",
        "forget",
        "sneaky",
        "daring",
        "riches",
        "hasten",
        "albeit",
        "pearly",
        "waiter",
        "Korean",
        "replay",
        "carpet",
        "pueblo",
        "brandy",
        "hunker",
        "recast",
        "insult",
        "around",
        "taking",
        "mantel",
        "parole",
        "infest",
        "lament",
        "binary",
        "mascot",
        "Trojan",
        "pelvis",
        "costly",
        "couple",
        "ethnic",
        "kindly",
        "throng",
        "whisky",
        "sliver",
        "dating",
        "sexual",
        "locust",
        "ponder",
        "serial",
        "action",
        "rocket",
        "parody",
        "hubris",
        "induct",
        "author",
        "verify",
        "musket",
        "pulsar",
        "tongue",
        "rapist",
        "squeal",
        "aching",
        "enough",
        "firmly",
        "bounty",
        "distal",
        "scrape",
        "format",
        "troupe",
        "praise",
        "salted",
        "staple",
        "bleach",
        "ravine",
        "robust",
        "dampen",
        "sprout",
        "ruling",
        "subway",
        "walker",
        "Latino",
        "recoil",
        "purist",
        "fiscal",
        "fluent",
        "yogurt",
        "optics",
        "wealth",
        "cloudy",
        "savory",
        "finder",
        "incest",
        "vulgar",
        "flaunt",
        "others",
        "nearly",
        "cavity",
        "myriad",
        "Yoruba",
        "vortex",
        "falter",
        "roving",
        "comply",
        "plenty",
        "factor",
        "triple",
        "ordeal",
        "weapon",
        "namely",
        "thorny",
        "squeak",
        "strand",
        "Labour",
        "awhile",
        "devout",
        "infect",
        "trench",
        "deacon",
        "handle",
        "unsafe",
        "jostle",
        "sample",
        "dancer",
        "gather",
        "neural",
        "import",
        "angled",
        "magnet",
        "Somali",
        "ambush",
        "pained",
        "bustle",
        "duplex",
        "lumber",
        "Quaker",
        "cinema",
        "father",
        "punter",
        "mating",
        "cartel",
        "orient",
        "fondly",
        "busily",
        "fasten",
        "weakly",
        "Soviet",
        "Libyan",
        "crazed",
        "silver",
        "lament",
        "autism",
        "junior",
        "phobia",
        "almond",
        "unseat",
        "Nazism",
        "nutmeg",
        "stream",
        "polish",
        "stride",
        "radish",
        "enrich",
        "busted",
        "basket",
        "gurney",
        "import",
        "clover",
        "bumper",
        "inject",
        "legacy",
        "beauty",
        "bounce",
        "butler",
        "flying",
        "abject",
        "coming",
        "unmask",
        "abuser",
        "fondle",
        "slower",
        "mildew",
        "charge",
        "sketch",
        "outlay",
        "smudge",
        "captor",
        "flavor",
        "outcry",
        "breast",
        "sailor",
        "jaunty",
        "invest",
        "curfew",
        "orange",
        "ingest",
        "ashore",
        "oblige",
        "acuity",
        "acquit",
        "hugely",
        "dictum",
        "ambush",
        "theirs",
        "rumble",
        "stance",
        "mirage",
        "advent",
        "fungal",
        "insult",
        "Soviet",
        "fiesta",
        "trudge",
        "wicker",
        "blouse",
        "ouster",
        "infuse",
        "fucker",
        "drowsy",
        "satire",
        "genius",
        "coarse",
        "shiver",
        "plunge",
        "breath",
        "locked",
        "upbeat",
        "luster",
        "mortal",
        "futile",
        "behind",
        "listed",
        "scribe",
        "simply",
        "mantle",
        "maiden",
        "snugly",
        "spider",
        "talker",
        "shared",
        "boiler",
        "spiral",
        "opiate",
        "rancid",
        "saucer",
        "nudity",
        "fickle",
        "waiver",
        "second",
        "induce",
        "fetish",
        "blazer",
        "wander",
        "mangle",
        "rustle",
        "motley",
        "pickle",
        "aspire",
        "primal",
        "vanish",
        "rustle",
        "plenty",
        "radius",
        "diaper",
        "dispel",
        "frayed",
        "mortal",
        "ethics",
        "behalf",
        "monkey",
        "unwrap",
        "podium",
        "fixate",
        "sanity",
        "grisly",
        "theory",
        "garlic",
        "impact",
        "sucker",
        "divest",
        "hamper",
        "voyage",
        "acumen",
        "public",
        "arouse",
        "psycho",
        "hanger",
        "piracy",
        "paying",
        "combat",
        "fright",
        "double",
        "domain",
        "update",
        "scream",
        "profit",
        "censor",
        "anemic",
        "lavish",
        "bounce",
        "binary",
        "doings",
        "glower",
        "pardon",
        "glider",
        "quiver",
        "boater",
        "relish",
        "rudely",
        "zombie",
        "septic",
        "alight",
        "smudge",
        "wreath",
        "docket",
        "strive",
        "derail",
        "stable",
        "outlaw",
        "picker",
        "copier",
        "mythic",
        "crusty",
        "tailor",
        "shrink",
        "hijack",
        "shaped",
        "gifted",
        "invoke",
        "parent",
        "planet",
        "Basque",
        "rustic",
        "bother",
        "mature",
        "hamper",
        "splice",
        "polity",
        "ritual",
        "result",
        "shriek",
        "bucket",
        "enamor",
        "voting",
        "opaque",
        "modify",
        "uplift",
        "buried",
        "racist",
        "remain",
        "brunch",
      ],

      rightletter: 0,
      inputarr: [], //input 数组
      world: "",
      letterarr: "",
    };
  },
  created() {
    // let rannum = Math.floor(Math.random() * 1444);
    this.inputarr = document.getElementsByClassName("inp");

    let firstwechat = new Date("2021/04/09/23:36").getTime();
    let nowtime = new Date();
    let firstdays = nowtime.getTime() - firstwechat,
      days = parseInt(firstdays / (1000 * 60 * 60 * 24));
    this.world = this.undoublearr[days - 312].toLowerCase();
    // this.world = this.world.toLowerCase()
    this.letterarr = this.world.split("");
  },
  methods: {
    befocus(ind) {
      this.inputarr[ind - 1].value = "";
    },
    upkey(e, i) {
      let reg = /^[A-Za-z]/;
      // 输入字母后跳到下一个
      if (i != 5) {
        if (reg.test(this.inputarr[i].value)) {
          if (this.inputarr[i + 1].value == "") {
            this.inputarr[i + 1].focus();
          }
        }
      }
      // 删除键删除上一个input
      if (e.keyCode == 8) {
        if (i != 0) {
          if (this.inputarr[i].value == "") {
            this.inputarr[i - 1].value = "";
            this.inputarr[i - 1].focus();
          }
        }
      }
    },
    def() {
      this.rightletter = 0;
      let enterWorld = "",
        ifInWorldArr = false;
      for (let i = 0; i < 6; i++) {
        enterWorld += this.inputarr[i].value;
      }

      this.enterarr.push(enterWorld);
      this.undoublearr.forEach((ele) => {
        if (ele.toLowerCase() == enterWorld) {
          ifInWorldArr = true;
        }
      });
      if (!ifInWorldArr) {
        alert("请输入正确的单词");
        navigator.vibrate(1000); // 手机震动
      } else {
        for (let i = 0; i < 6; i++) {
          this.deal(this.inputarr[i].value, this.letterarr[i]);
          this.inputarr[i].value = "";
        }
      }
    
      if (this.rightletter == 6) {
        alert("答对了");
      } else {
        if (this.enterarr.length == 5) {
          alert("很遗憾5次机会用尽了，这个单词是" + world);
        }
      }
    },

    deal(invalue, num) {   
      if (invalue == num) {
        this.rightletter++;     
        let keyword = document.getElementById(invalue);
        keyword.style.backgroundColor = "#67C23A";
      } else {
        let ifhave = false;
        this.letterarr.forEach((ele) => {
          if (invalue == ele) {       
            let keyword = document.getElementById(invalue);
            keyword.style.backgroundColor = "#E6A23C";
            ifhave = true;
          }
        });
        if (!ifhave) {         
          let keyword = document.getElementById(invalue);
          keyword.style.backgroundColor = "#F56C6C";
        }
      }   
    },
  },
};
</script>

<style scoped>
.row {
  display: flex;
  justify-content: center;
  margin-bottom: 7px;
}

.let {
  margin: 0 5px;
  display: inline-block;
  height: 35px;
  width: 25px;
  border-radius: 5px;
  line-height: 30px;
  font-size: 30px;
  border: 2px solid white;
  text-align: center;
  background-color: black;
  color: white;
}

.rules {
  margin-bottom: 15px;
}

.inp {
  display: inline-block;
  flex-grow: 0;
  width: 35px;
  height: 35px;
  line-height: 35px;
  font-size: 30px;
  text-align: center;
  margin: 0 5px;
  border-radius: 8px;
}

.butt,
.myform {
  display: flex;
  justify-content: center;
}

.downlet {
  background-color: black;
  height: 40px;
  line-height: 40px;
  width: 40px;
  display: inline-block;
  color: white;
  font-size: 30px;
  text-align: center;
  margin-right: 5px;
  margin-left: 5px;
  border-radius: 2px;
  margin-bottom: 5px;
}

.have {
  background-color: #e6a23c;
}

.true {
  background-color: #67c23a;
}

.unhave {
  background-color: #f56c6c;
}

.confirm {
  margin: auto;
  margin-top: 15px;
  margin-bottom: 15px;
  background-color: pink;
  color: white;
  border: none;
  height: 50px;
  line-height: 50px;
  /* width: 80px; */
  font-size: 30px;
  border-radius: 15px;
}
</style>
